---
- hosts: webservers
  amazon.aws.ec2_metadata_facts:
  tasks:

    - name: Install maven
      become: yes
      apt:
        name: maven
        state: present
        update_cache: yes

    - name: Copy files
      copy:
        src: ./app
        dest: ~/
        remote_src: no

    - name: Edit application.properties
      lineinfile:
        search_string: suchname=Name
        line: "suchname=${{ ansible_ec2_placement_availability_zone }}"
        path: ~/src/main/resources/application.properties

    - name: Run maven install
      shell: |
        mvn package
      args:
        chdir: ~/app

    - name: Start Java app
      shell:
        java -jar <app-name>.jar
      args:
        chdir: ~/app/targets/
