name: Deploy Application
on:
  push:
    branches:
      - prod
      - dev
      - sta
      - acc

jobs:
  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - name: SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get bastion host
        run: export bastion=$(ansible-inventory -i environments/${{ steps.branch-name.outputs.current_branch }}/aws_ec2.yml --list | jq -r '.tag_Name_Bastion.hosts[0]')
          
      - name: Install SSH key of bastion
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          name: id_rsa
          known_hosts: unnecessary
          if_key_exists: ignore
          config: |
            Host bastion
              HostName ${{ secrets.BASTION }}
              User ubuntu

      - name: Generate known_hosts for webservers
        run: |
          echo "$(ansible-inventory -i environments/${{ steps.branch-name.outputs.current_branch }}/aws_ec2.yml --list | jq -r '.tag_Name_Webservers.hosts[]' )" > hosts
          echo "$(ansible-inventory -i environments/${{ steps.branch-name.outputs.current_branch }}/aws_ec2.yml --list | jq -r '.tag_Name_Webservers.hosts[]' )" >> environments/${{ steps.branch-name.outputs.current_branch }}/inv
          for host in $(cat hosts); do
          cat << EOF >> ~/.ssh/config
          Host $host
              Hostname $host
              IdentityFile ~/.ssh/id_rsa
              ProxyCommand ssh -W %h:%p bastion
          EOF
          done

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          options: |
            --inventory environments/${{ steps.branch-name.outputs.current_branch }}/inv